[package]
name = "lianghua-app-data"
version = "0.1.0"
edition = "2024"

[dependencies]
lianghua-app-shared = { path = "../lianghua-app-shared" }
lianghua-core = { path = "../lianghua-core" }
lianghua-data = { path = "../lianghua-data" }
lianghua-download = { path = "../lianghua-download" }
chrono = "0.4.44"
duckdb = { version = "1.4.4", features = ["appender-arrow"] }
rayon = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
